import type { OwnerLanguage } from "./owner.js";

const COPY = {
  en: {
    "session.open": "Gold is open.",
    "session.closed_saturday": "Gold is closed for the weekend.",
    "session.closed_friday": "Gold is closed after the New York Friday finish.",
    "session.closed_sunday": "Gold has not opened yet this week.",
    "session.maintenance_break": "Gold is in the daily maintenance break.",
    "session.center.sydney": "Sydney",
    "session.center.tokyo": "Tokyo",
    "session.center.london": "London",
    "session.center.newyork": "New York",
    "session.oneOpen": "is open.",
    "session.manyOpen": "are open.",
    "session.severalOpen": "are open.",
    "session.centersNone": "No major center is open.",
    "session.centersNext": "Next:",
    "session.overlap.sydney_tokyo": "Sydney and Tokyo overlap.",
    "session.overlap.tokyo_london": "Tokyo and London overlap.",
    "session.overlap.london_newyork": "London and New York overlap.",
    "status.running": "Lonora is running.",
    "tasks.paused": "Paused.",
    "tasks.resumed": "Resumed.",
    "tasks.cancelled": "Cancelled.",
    "notify.unchanged": "No meaningful gold change.",
    "notify.telegramMissing": "Telegram is not bound, so this notice stayed here.",
    "notify.deliveryFailed": "Telegram did not accept the notice.",
    "notify.sessionClosed": "The gold session changed while the market is closed.",
    "notify.macro": "A high-impact gold event is near.",
    "notify.headline": "Gold headlines changed.",
    "notify.price": "Gold price moved.",
    "notify.session": "The gold session changed.",
    "notify.volatility": "Gold volatility changed.",
    "notify.structure": "Gold structure changed.",
    "notify.sweep": "A liquidity sweep printed on a closed candle.",
    "notify.recommendation": "A gold recommendation changed.",
    "tasks.waitingClosed": "Market is closed. Waiting for the next open.",
    "tasks.waiting": "Still waiting. Nothing in this check matched the instruction.",
    "tasks.matched": "Matched",
    "tasks.scheduled": "Scheduled",
    "tasks.scheduleRejected":
      "The scheduler did not accept this briefing. The monitor will still check it.",
    "trade.blocked": "Lonora will not place that trade. Only you can confirm an order.",
    "recommendations.unreadable":
      "The stored activation rule could not be read, so this plan will not fill.",
    "calendar.empty": "No gold-relevant high or medium events are on the calendar in this window.",
    "calendar.unavailable": "No economic calendar is available. Lonora will not invent an event.",
    "plan.insufficient": "Closed candles are not enough to place a protected stop.",
    "plan.noZone": "No supply or demand zone is available, so no plan was prepared.",
    "plan.zoneWeak": "The nearest zones are not tradable, so no plan was prepared.",
    "plan.noTarget": "No structural target clears the distance floor, so no plan was prepared.",
    "plan.invalid": "The zone does not produce a valid stop, so no plan was prepared.",
    "plan.stopBeyond": "Stop sits beyond the structural level",
    "plan.widened": "The distance floor pushed it farther out.",
    "plan.grade": "Zone grade",
    "plan.targets": "Structural targets",
    "plan.spreadUnread": "The spread was not read, so this reward is not net of cost.",
    "risk.incomplete": "No open gold plan has a stop and a first target.",
    "risk.gross": "First target is",
    "plan.spreadNet": "Net reward after spread",
    "plan.spreadWeak": "The first target does not pay the spread.",
    "plan.htfUnknown": "The higher timeframe was not read.",
    "mtf.bullish": "The four-hour read is up.",
    "mtf.bearish": "The four-hour read is down.",
    "mtf.aligned": "The working timeframe agrees with that read.",
    "mtf.conflict": "The working timeframe does not agree with that read.",
    "mtf.trendUnread": "The working timeframe trend was not read.",
    "plan.htfConflict": "The higher timeframe conflicts with this direction.",
    "plan.htfAligned": "The higher timeframe agrees with this direction.",
    "plan.pathBroken": "Price already broke the entry zone, so no plan was prepared.",
    "plan.pathUnlikely":
      "Price is moving away from the pending zone. This is not a trade in the other direction.",
    "plan.pathNeutral":
      "The idea waits for price to return to the zone. The path is not a trade the other way.",
    "plan.rangeWait": "That location does not favor an immediate entry. The direction stays.",
    "plan.closedScenario": "Gold is closed. This plan waits for the next open at",
    "plan.closedClock": "New York.",
    "range.premium": "Price is in the premium of",
    "range.discount": "Price is in the discount of",
    "range.mid": "Price is mid-range in",
    "range.nearHigh": "Price is near the high of",
    "range.nearLow": "Price is near the low of",
    "cases.insufficient": "Closed history is too short to compare with earlier gold moments.",
    "cases.none": "No earlier gold moment is similar enough to count.",
    "cases.counts": "Similar moments are too few for a rate",
    "cases.rate": "Resolved similar moments",
    "headlines.unavailable":
      "Gold headlines are not available. Lonora will not invent a quiet tape.",
    "headlines.empty": "No gold-relevant headlines are in this window.",
    "memory.empty": "No gold memory is stored yet.",
    "memory.lead": "Gold memory.",
    "memory.scenario": "Scenario:",
    "memory.lessons": "Lessons:",
    "memory.observation": "Latest observation:",
    "memory.structure": "Latest structure:",
    "memory.liquidity": "Latest liquidity:",
    "memory.zones": "Latest zones:",
    "memory.timeframe": "Higher timeframe:",
    "memory.plans": "Open plans:",
    "memory.risk": "Plan grade:",
    "purpose.marketWatcher":
      "Watch gold for material changes without calling a model every candle.",
    "purpose.structure": "Read swings, trend, and structure breaks from closed candles.",
    "purpose.liquidity": "Locate equal highs and lows where stops are likely resting.",
    "purpose.zones": "Mark impulse supply and demand zones.",
    "purpose.mtf":
      "Compare the working timeframe with the four-hour read. A short sample stays unread.",
    "purpose.macro": "Read the economic calendar and gold headlines. A failed feed stays unknown.",
    "purpose.risk":
      "Grade the open plan's first target against its stop. A missing spread is not a net reward.",
    "purpose.research":
      "Compare earlier closed gold moments. A small sample does not become a rate.",
    "purpose.memory": "Compact a lesson so later responsibilities stay small.",
    "purpose.guardian": "Keep delegation limits and the manual trade boundary intact.",
    "name.marketWatcher": "Market Watcher",
    "name.structure": "Structure",
    "name.liquidity": "Liquidity",
    "name.zones": "Supply and demand",
    "name.mtf": "Multi-timeframe",
    "name.macro": "Macro and news",
    "name.risk": "Risk",
    "name.research": "Research",
    "name.memory": "Memory",
    "name.guardian": "Guardian",
    "state.running": "Running",
    "state.onDemand": "On demand",
    "memory.conversation": "Last request:",
    "memory.buy": "buy",
    "memory.sell": "sell",
    "memory.planStop": "stop",
    "memory.planTarget": "target",
    "memory.tasks": "Responsibilities:",
    "memory.stored": "The lesson is stored.",
    "memory.none": "No new lesson was supplied.",
    "guardian.unchecked": "The guardian did not read the live limits.",
    "guardian.failed": "The trade boundary is not intact.",
    "guardian.runs": "Specialist runs in the last minute:",
    "guardian.cap": "The cap is",
    "guardian.tradeBlocked": "Model trade is blocked.",
    "guardian.broker": "A confirmed owner order is not linked to a broker.",
    "guardian.coding": "Coding tools stay blocked.",
    "entry.retest": "The fill is a return into",
    "entry.retestMissing": "This retest has no usable band, so it will not fill.",
    "structure.prior": "Prior gold day",
    "structure.short": "Not enough closed candles to read structure.",
    "structure.noBreak": "No fresh close beyond a swing.",
    "structure.bos": "Break of structure",
    "structure.choch": "Change of character",
    "structure.mss": "Market structure shift",
    "structure.bullish": "up",
    "structure.bearish": "down",
    "structure.at": "at",
    "structure.trend.uptrend": "Uptrend",
    "structure.trend.downtrend": "Downtrend",
    "structure.trend.range": "Range",
    "structure.trend.unknown": "Trend unread",
    "liquidity.short": "Closed candles are too short to locate resting liquidity.",
    "liquidity.none": "No equal high or low, and no sweep, in these closed candles.",
    "liquidity.buy": "Resting buy-side",
    "liquidity.sell": "Resting sell-side",
    "liquidity.sweepBuy": "Buy-side sweep of",
    "liquidity.sweepSell": "Sell-side sweep of",
    "liquidity.inside": "The close came back inside.",
    "zones.short": "Closed candles are too short to mark supply and demand.",
    "zones.none": "No supply or demand zone in these closed candles.",
    "zones.demand": "Demand",
    "zones.supply": "Supply",
    "zones.grade": "grade",
    "zones.tradable": "tradable",
    "zones.notTradable": "not tradable",
    "zones.ungraded": "not graded",
    "pattern.unclassified": "The swing range is not classified yet.",
    "pattern.starting": "A swing range is starting.",
    "pattern.forming": "A swing range is forming.",
    "pattern.near": "A swing range is near completion.",
    "pattern.completed": "A close moved beyond the swing range. Confirmation is still open.",
    "pattern.confirmed": "A later close confirmed the move beyond the swing range.",
    "pattern.failed": "The swing range failed.",
    "pattern.doubleTop": "Double top",
    "pattern.doubleBottom": "Double bottom",
    "pattern.tripleTop": "Triple top",
    "pattern.tripleBottom": "Triple bottom",
    "pattern.headShoulders": "Head and shoulders",
    "pattern.inverseHeadShoulders": "Inverse head and shoulders",
    "pattern.ascending": "Ascending triangle",
    "pattern.descending": "Descending triangle",
    "pattern.symmetrical": "Symmetrical triangle",
    "pattern.risingWedge": "Rising wedge",
    "pattern.fallingWedge": "Falling wedge",
    "pattern.flag": "Flag",
    "pattern.pennant": "Pennant",
    "pattern.cup": "Cup and handle",
    "pattern.inverseCup": "Inverse cup and handle",
    "pattern.rectangle": "Rectangle",
    "pattern.support": "Support",
    "pattern.resistance": "Resistance",
    "pattern.risingChannel": "Rising channel",
    "pattern.fallingChannel": "Falling channel",
    "pattern.horizontalChannel": "Horizontal channel",
    "candle.none": "No named candle on the latest close.",
    "candle.notATrade": "Not a trade.",
    "candle.doji": "Doji",
    "candle.hammer": "Hammer",
    "candle.inverted_hammer": "Inverted hammer",
    "candle.shooting_star": "Shooting star",
    "candle.hanging_man": "Hanging man",
    "candle.marubozu_bullish": "Bullish marubozu",
    "candle.marubozu_bearish": "Bearish marubozu",
    "candle.spinning_top": "Spinning top",
    "candle.bullish_engulfing": "Bullish engulfing",
    "candle.bearish_engulfing": "Bearish engulfing",
    "candle.morning_star": "Morning star",
    "candle.evening_star": "Evening star",
    "candle.three_white_soldiers": "Three white soldiers",
    "candle.three_black_crows": "Three black crows",
    "candle.bullish_harami": "Bullish harami",
    "candle.bearish_harami": "Bearish harami",
    "candle.tweezer_top": "Tweezer top",
    "candle.tweezer_bottom": "Tweezer bottom",
  },
  ar: {
    "session.open": "سوق الذهب مفتوح.",
    "session.closed_saturday": "الذهب مغلق لعطلة نهاية الأسبوع.",
    "session.closed_friday": "الذهب مغلق بعد إغلاق جمعة نيويورك.",
    "session.closed_sunday": "الذهب لم يفتح بعد هذا الأسبوع.",
    "session.maintenance_break": "الذهب في استراحة الصيانة اليومية.",
    "session.center.sydney": "سيدني",
    "session.center.tokyo": "طوكيو",
    "session.center.london": "لندن",
    "session.center.newyork": "نيويورك",
    "session.oneOpen": "مفتوحة.",
    "session.manyOpen": "مفتوحتان.",
    "session.severalOpen": "مفتوحات.",
    "session.centersNone": "لا مركز رئيسي مفتوح.",
    "session.centersNext": "التالي:",
    "session.overlap.sydney_tokyo": "تداخل سيدني وطوكيو.",
    "session.overlap.tokyo_london": "تداخل طوكيو ولندن.",
    "session.overlap.london_newyork": "تداخل لندن ونيويورك.",
    "status.running": "لونورا تعمل.",
    "tasks.paused": "تم الإيقاف المؤقت.",
    "tasks.resumed": "استؤنفت المهمة.",
    "tasks.cancelled": "أُلغيت المهمة.",
    "notify.unchanged": "لا تغيير مهم في الذهب.",
    "notify.telegramMissing": "تيليجرام غير مربوط، فبقي التنبيه هنا.",
    "notify.deliveryFailed": "تيليجرام لم يقبل التنبيه.",
    "notify.sessionClosed": "تغيّرت جلسة الذهب والسوق مغلق.",
    "notify.macro": "حدث ذهبي عالي التأثير اقترب.",
    "notify.headline": "تغيرت عناوين الذهب.",
    "notify.price": "تحرّك سعر الذهب.",
    "notify.session": "تغيّرت جلسة الذهب.",
    "notify.volatility": "تغيّر تقلب الذهب.",
    "notify.structure": "تغيّر هيكل الذهب.",
    "notify.sweep": "ظهر سحب سيولة على شمعة مغلقة.",
    "notify.recommendation": "تغيّرت توصية ذهب.",
    "tasks.waitingClosed": "السوق مغلق. الانتظار حتى الفتح التالي.",
    "tasks.waiting": "ما زال الانتظار. هذا الفحص لا يطابق التعليمات.",
    "tasks.matched": "تطابق",
    "tasks.scheduled": "مجدول",
    "tasks.scheduleRejected": "المجدول لم يقبل الإحاطة. المراقبة ستستمر في فحصها.",
    "trade.blocked": "لونورا لن تنفّذ هذه الصفقة. التأكيد اليدوي لك وحدك.",
    "recommendations.unreadable": "تعذر قراءة شرط التفعيل المخزّن، لذلك لن تُملأ هذه الخطة.",
    "calendar.empty": "لا أحداث عالية أو متوسطة ذات صلة بالذهب في هذه النافذة.",
    "calendar.unavailable": "التقويم الاقتصادي غير متاح. لن تخترع لونورا حدثاً.",
    "plan.insufficient": "الشموع المغلقة لا تكفي لوضع وقف محمي.",
    "plan.noZone": "لا توجد منطقة عرض أو طلب، لذلك لم تُجهَّز خطة.",
    "plan.zoneWeak": "المناطق القريبة غير قابلة للتداول، لذلك لم تُجهَّز خطة.",
    "plan.noTarget": "لا يوجد هدف هيكلي يجتاز حد المسافة، لذلك لم تُجهَّز خطة.",
    "plan.invalid": "المنطقة لا تنتج وقفاً صالحاً، لذلك لم تُجهَّز خطة.",
    "plan.stopBeyond": "الوقف يقع بعد المستوى الهيكلي",
    "plan.widened": "حد المسافة دفعه أبعد.",
    "plan.grade": "درجة المنطقة",
    "plan.targets": "أهداف هيكلية",
    "plan.spreadUnread": "السبريد لم يُقرأ، لذلك هذه المكافأة ليست صافية من التكلفة.",
    "risk.incomplete": "لا خطة ذهب مفتوحة فيها وقف وهدف أول.",
    "risk.gross": "الهدف الأول",
    "plan.spreadNet": "المكافأة الصافية بعد السبريد",
    "plan.spreadWeak": "الهدف الأول لا يغطي السبريد.",
    "plan.htfUnknown": "الإطار الزمني الأعلى لم يُقرأ.",
    "mtf.bullish": "قراءة أربع ساعات صاعدة.",
    "mtf.bearish": "قراءة أربع ساعات هابطة.",
    "mtf.aligned": "الإطار العامل يوافق هذه القراءة.",
    "mtf.conflict": "الإطار العامل لا يوافق هذه القراءة.",
    "mtf.trendUnread": "اتجاه الإطار العامل لم يُقرأ.",
    "plan.htfConflict": "الإطار الزمني الأعلى يتعارض مع هذا الاتجاه.",
    "plan.htfAligned": "الإطار الزمني الأعلى يوافق هذا الاتجاه.",
    "plan.pathBroken": "السعر اخترق منطقة الدخول، لذلك لم تُجهَّز خطة.",
    "plan.pathUnlikely": "السعر يبتعد عن المنطقة المعلقة. هذا ليس صفقة في الاتجاه المعاكس.",
    "plan.pathNeutral": "الفكرة تنتظر عودة السعر إلى المنطقة. المسار ليس صفقة في الاتجاه المعاكس.",
    "plan.rangeWait": "هذا الموقع لا يفضّل دخولاً فورياً. الاتجاه يبقى.",
    "plan.closedScenario": "الذهب مغلق. هذه الخطة تنتظر الفتح التالي عند",
    "plan.closedClock": "بتوقيت نيويورك.",
    "range.premium": "السعر في منطقة العلاوة ضمن",
    "range.discount": "السعر في منطقة الخصم ضمن",
    "range.mid": "السعر في منتصف النطاق",
    "range.nearHigh": "السعر قرب قمة النطاق",
    "range.nearLow": "السعر قرب قاع النطاق",
    "cases.insufficient": "التاريخ المغلق أقصر من أن يُقارن بلحظات ذهب سابقة.",
    "cases.none": "لا توجد لحظة ذهب سابقة قريبة بما يكفي.",
    "cases.counts": "اللحظات المتشابهة أقل من أن تُنتج نسبة",
    "cases.rate": "لحظات متشابهة محسومة",
    "headlines.unavailable": "عناوين الذهب غير متاحة. لن تخترع لونورا شريطاً هادئاً.",
    "headlines.empty": "لا عناوين ذات صلة بالذهب في هذه النافذة.",
    "memory.empty": "لا ذاكرة ذهب مخزّنة بعد.",
    "memory.lead": "ذاكرة الذهب.",
    "memory.scenario": "السيناريو:",
    "memory.lessons": "الدروس:",
    "memory.observation": "آخر ملاحظة:",
    "memory.structure": "آخر قراءة:",
    "memory.liquidity": "آخر سيولة:",
    "memory.zones": "آخر مناطق:",
    "memory.timeframe": "الإطار الأعلى:",
    "memory.plans": "خطط مفتوحة:",
    "memory.risk": "درجة الخطة:",
    "purpose.marketWatcher": "يراقب الذهب للتغيّر المهم دون استدعاء نموذج عند كل شمعة.",
    "purpose.structure": "يقرأ التأرجح والاتجاه وكسور الهيكل من الشموع المغلقة.",
    "purpose.liquidity": "يحدد القمم والقيعان المتساوية حيث ترجح وقوف الأوامر.",
    "purpose.zones": "يعلّم مناطق العرض والطلب الناتجة عن اندفاع.",
    "purpose.mtf": "يقارن الإطار العامل بقراءة أربع ساعات. العينة القصيرة تبقى غير مقروءة.",
    "purpose.macro": "يقرأ التقويم الاقتصادي وعناوين الذهب. التغذية الفاشلة تبقى مجهولة.",
    "purpose.risk":
      "يقيس هدف الخطة المفتوحة الأول مقابل الوقف. السبريد غير المقروء ليس مكافأة صافية.",
    "purpose.research": "يقارن لحظات ذهب مغلقة سابقة. العينة الصغيرة لا تصبح نسبة.",
    "purpose.memory": "يختصر الدرس حتى تبقى المسؤوليات اللاحقة صغيرة.",
    "purpose.guardian": "يحافظ على حدود التفويض وحد التنفيذ اليدوي.",
    "name.marketWatcher": "مراقب السوق",
    "name.structure": "الهيكل",
    "name.liquidity": "السيولة",
    "name.zones": "العرض والطلب",
    "name.mtf": "الأطر الزمنية",
    "name.macro": "الاقتصاد والعناوين",
    "name.risk": "المخاطر",
    "name.research": "البحث",
    "name.memory": "الذاكرة",
    "name.guardian": "الحارس",
    "state.running": "يعمل",
    "state.onDemand": "عند الطلب",
    "memory.conversation": "آخر طلب:",
    "memory.buy": "شراء",
    "memory.sell": "بيع",
    "memory.planStop": "وقف",
    "memory.planTarget": "هدف",
    "memory.tasks": "المسؤوليات:",
    "memory.stored": "تم حفظ الدرس.",
    "memory.none": "لم يُقدَّم درس جديد.",
    "guardian.unchecked": "الحارس لم يقرأ الحدود الحية.",
    "guardian.failed": "حد التنفيذ غير سليم.",
    "guardian.runs": "تشغيلات المتخصصين في الدقيقة الأخيرة:",
    "guardian.cap": "السقف",
    "guardian.tradeBlocked": "تنفيذ النموذج محظور.",
    "guardian.broker": "تأكيد المالك لا يتصل بوسيط.",
    "guardian.coding": "أدوات البرمجة تبقى محظورة.",
    "entry.retest": "الدخول عند العودة إلى",
    "entry.retestMissing": "إعادة الاختبار بلا نطاق صالح، لذلك لن تُملأ.",
    "structure.prior": "يوم الذهب السابق",
    "structure.short": "الشموع المغلقة لا تكفي لقراءة الهيكل.",
    "structure.noBreak": "لا إغلاق جديد يتجاوز سوينغاً.",
    "structure.bos": "كسر هيكل",
    "structure.choch": "تغيّر شخصية",
    "structure.mss": "انزياح هيكل",
    "structure.bullish": "صاعد",
    "structure.bearish": "هابط",
    "structure.at": "عند",
    "structure.trend.uptrend": "اتجاه صاعد",
    "structure.trend.downtrend": "اتجاه هابط",
    "structure.trend.range": "نطاق",
    "structure.trend.unknown": "الاتجاه غير مقروء",
    "liquidity.short": "الشموع المغلقة أقصر من أن تُظهر سيولة راكدة.",
    "liquidity.none": "لا قمة أو قاع متساويان، ولا مسح، في هذه الشموع المغلقة.",
    "liquidity.buy": "سيولة شرائية راكدة",
    "liquidity.sell": "سيولة بيعية راكدة",
    "liquidity.sweepBuy": "مسح سيولة شرائية عند",
    "liquidity.sweepSell": "مسح سيولة بيعية عند",
    "liquidity.inside": "الإغلاق عاد إلى الداخل.",
    "zones.short": "الشموع المغلقة أقصر من أن تُظهر عرضاً أو طلباً.",
    "zones.none": "لا منطقة عرض أو طلب في هذه الشموع المغلقة.",
    "zones.demand": "طلب",
    "zones.supply": "عرض",
    "zones.grade": "درجة",
    "zones.tradable": "قابلة للتداول",
    "zones.notTradable": "غير قابلة للتداول",
    "zones.ungraded": "بلا درجة",
    "pattern.unclassified": "نطاق التأرجح لم يُصنَّف بعد.",
    "pattern.starting": "نطاق تأرجح بدأ يتكوّن.",
    "pattern.forming": "نطاق تأرجح قيد التكوّن.",
    "pattern.near": "نطاق التأرجح قارب الاكتمال.",
    "pattern.completed": "إغلاق تجاوز نطاق التأرجح. التأكيد ما زال مفتوحاً.",
    "pattern.confirmed": "إغلاق لاحق أكّد الحركة خارج نطاق التأرجح.",
    "pattern.failed": "فشل نطاق التأرجح.",
    "pattern.doubleTop": "قمة مزدوجة",
    "pattern.doubleBottom": "قاع مزدوج",
    "pattern.tripleTop": "قمة ثلاثية",
    "pattern.tripleBottom": "قاع ثلاثي",
    "pattern.headShoulders": "رأس وكتفان",
    "pattern.inverseHeadShoulders": "رأس وكتفان مقلوبان",
    "pattern.ascending": "مثلث صاعد",
    "pattern.descending": "مثلث هابط",
    "pattern.symmetrical": "مثلث متماثل",
    "pattern.risingWedge": "وتد صاعد",
    "pattern.fallingWedge": "وتد هابط",
    "pattern.flag": "علم",
    "pattern.pennant": "راية",
    "pattern.cup": "كوب وعروة",
    "pattern.inverseCup": "كوب وعروة مقلوبان",
    "pattern.rectangle": "مستطيل",
    "pattern.support": "دعم",
    "pattern.resistance": "مقاومة",
    "pattern.risingChannel": "قناة صاعدة",
    "pattern.fallingChannel": "قناة هابطة",
    "pattern.horizontalChannel": "قناة أفقية",
    "candle.none": "لا شمعة مسماة على آخر إغلاق.",
    "candle.notATrade": "ليست صفقة.",
    "candle.doji": "دوجي",
    "candle.hammer": "مطرقة",
    "candle.inverted_hammer": "مطرقة مقلوبة",
    "candle.shooting_star": "نجمة ساقطة",
    "candle.hanging_man": "رجل مشنوق",
    "candle.marubozu_bullish": "ماروبوزو صاعد",
    "candle.marubozu_bearish": "ماروبوزو هابط",
    "candle.spinning_top": "قمة دوارة",
    "candle.bullish_engulfing": "ابتلاع صاعد",
    "candle.bearish_engulfing": "ابتلاع هابط",
    "candle.morning_star": "نجمة الصباح",
    "candle.evening_star": "نجمة المساء",
    "candle.three_white_soldiers": "ثلاثة جنود بيض",
    "candle.three_black_crows": "ثلاثة غربان سود",
    "candle.bullish_harami": "هارامي صاعد",
    "candle.bearish_harami": "هارامي هابط",
    "candle.tweezer_top": "ملقط علوي",
    "candle.tweezer_bottom": "ملقط سفلي",
  },
} as const;

export type CopyKey = keyof (typeof COPY)["en"];

export function copy(language: OwnerLanguage, key: CopyKey): string {
  return COPY[language][key] ?? COPY.en[key];
}

/** Owner text for one monitor notice. Internal reason codes stay off the message. */
export function describeNotice(language: OwnerLanguage, key: string): string {
  if (key.startsWith("session:")) {
    return copy(language, "notify.sessionClosed");
  }
  if (key.startsWith("macro_event:")) {
    return copy(language, "notify.macro");
  }
  if (key.startsWith("headline:")) {
    return copy(language, "notify.headline");
  }
  switch (key.split(":")[0]) {
    case "price_move":
      return copy(language, "notify.price");
    case "session_transition":
      return copy(language, "notify.session");
    case "volatility_change":
      return copy(language, "notify.volatility");
    case "structure_change":
      return copy(language, "notify.structure");
    case "liquidity_sweep":
      return copy(language, "notify.sweep");
    case "recommendation_change":
      return copy(language, "notify.recommendation");
    default:
      return copy(language, "notify.unchanged");
  }
}

export function marketReasonCopy(
  language: OwnerLanguage,
  reason: "open" | "saturday" | "friday_close" | "sunday" | "maintenance",
): string {
  switch (reason) {
    case "open":
      return copy(language, "session.open");
    case "saturday":
      return copy(language, "session.closed_saturday");
    case "friday_close":
      return copy(language, "session.closed_friday");
    case "sunday":
      return copy(language, "session.closed_sunday");
    case "maintenance":
      return copy(language, "session.maintenance_break");
  }
}
